import { DocumentBuilder } from '@nestjs/swagger';

export const swaggerConfig = new DocumentBuilder()
  .setTitle('Bookstore API')
  .setDescription('E-commerce API for bookstore application')
  .setVersion('1.0')
  .addBearerAuth()
  .addTag('health', 'Health check endpoints')
  .addTag('auth', 'Authentication - Register and login')
  .addTag('books', 'Book catalog and search')
  .addTag('authors', 'Authors management')
  .addTag('categories', 'Book categories')
  .addTag('publishers', 'Publishers information')
  .addTag('orders', 'Order management')
  .addTag('cart', 'Shopping cart')
  .addTag('reviews', 'Book reviews and ratings')
  .addTag('addresses', 'Shipping addresses')
  .addTag('reports', 'Reports and analytics (admin only)')
  .addTag('users', 'User management (admin only)')
  .build();
